name: main_text_field
description: "A customizable Flutter form field widget for inputs like text, email, password, and phone, offering validation, appearance options, and keyboard interaction support."
version: 0.0.1
homepage: https://github.com/abdelrahmanghanem
repository: https://github.com/abdelrahmanghanem/main_text_field
environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:

  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:

  # To add assets to your package, add an assets section, like this:
   assets:
     - packages/main_text_field/src/translation/en.json
     - packages/main_text_field/src/translation/ar.json


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

