name: main_text_field
description: "is a Flutter widget providing advanced customization for text input fields, ideal for developers needing flexible styling, validation, icons, and input control."
version: 0.0.1
homepage: https://github.com/abdelrahmanghanem
repository: https://github.com/abdelrahmanghanem/main_text_field.git
environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:

  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:

  # To add assets to your package, add an assets section, like this:
   assets:
     - packages/main_text_field/src/translation/en.json
     - packages/main_text_field/src/translation/ar.json
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
