name: main_text_field
description: "A customizable Flutter form field widget for inputs like text, email, password, and phone, offering validation, appearance options, and keyboard interaction support."
version: 0.0.4
homepage: https://github.com/abdelrahmanghanem
repository: https://github.com/abdelrahmanghanem/main_text_field
environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:

  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  country_code_picker: ^3.0.0
  smart_localize: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:

  assets:
    - assets/images/